version: '2'
services:
  service:
    container_name: stocks.example.com
    build: 
        context: .
        dockerfile: service/Dockerfile
    ports:
     - "9000:9000"
  esb:
    container_name: esb.example.com
    build:
      context: .
      dockerfile: esb/Dockerfile
    ports:
      - "9764:9763"
      - "9444:9443"
      - "8281:8280"
      - "8244:8243"
      - "9999:9999"
      - "11111:11111"
